// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsbvghwfvksfsozygkpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzYnZnaHdmdmtzZnNvenlna3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxMDE0OTUsImV4cCI6MjA1MTY3NzQ5NX0.NYfW4K1nJhusFixYr3sWtGR1s7soj_QbhZeq_BWJxjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);